### ISSUE TITLE
Typo in the GSoD Proposal

### ISSUE THREAD

**Issue by aniketsingh98571** [moja-global/Google_Season_of_Documentation#11]
![Screenshot (153)_LI](https://user-images.githubusercontent.com/63097956/114726473-0c5df100-9d5b-11eb-9be8-c8eef468525d.jpg)

@gmajan @shubhamkarande13 This needs to be solved for maintaining proper typography regarding the project proposal.

**Comment by shubhamkarande13** [comment]
FLINT indeed stands for the Full Lands INtegration Tool, so I do not see a reason for this issue.

Thank you for your concern regarding this. Please close this issue.

**Comment by aniketsingh98571** [comment]
Okay.
